Add maxHeaderSize to types
Adds the `.maxHeaderSize` field to the types of the `HTTPParserJS` class, otherwise tsc complains that the field doesn't exist.

Fixes this sort of thing:

```ts
const parser = new HTTPParser('RESPONSE')
parser.maxHeaderSize = 1024 * 1024
// error TS2339: Property 'maxHeaderSize' does not exist on type 'HTTPParserJS'
```